USE [master]
GO

/****** Object:  Database [depozit]    Script Date: 1/28/2023 9:16:09 PM ******/
CREATE DATABASE [depozit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'depozit', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\depozit.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'depozit_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\depozit_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [depozit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [depozit] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [depozit] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [depozit] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [depozit] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [depozit] SET ARITHABORT OFF 
GO

ALTER DATABASE [depozit] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [depozit] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [depozit] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [depozit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [depozit] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [depozit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [depozit] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [depozit] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [depozit] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [depozit] SET  DISABLE_BROKER 
GO

ALTER DATABASE [depozit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [depozit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [depozit] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [depozit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [depozit] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [depozit] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [depozit] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [depozit] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [depozit] SET  MULTI_USER 
GO

ALTER DATABASE [depozit] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [depozit] SET DB_CHAINING OFF 
GO

ALTER DATABASE [depozit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [depozit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [depozit] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [depozit] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [depozit] SET QUERY_STORE = OFF
GO

ALTER DATABASE [depozit] SET  READ_WRITE 
GO

